# This is a simple CodeBuild build file for PowerShell.
#  - pre_build step will ensure the Module Name / Version has not previously been built for production
#  - build step will perform the script analysis, pester tests, and Module compilation for publishing

version: 0.2

phases:
  install:
    commands:
      - '& dir'
      - powershell -command '.\configure_aws_credential.ps1'
      - aws s3 cp s3://ps-invoke-modules/PowerShell-6.1.1-win-x64.msi PowerShell-6.1.1-win-x64.msi --quiet
      - powershell -command "Start-Process .\PowerShell-6.1.1-win-x64.msi -ArgumentList '/qn /norestart' -Wait"
      #- powershell -command 'Get-CimInstance -ClassName Win32_Product'
      #- powershell -command "$global:poshcore = 'C:\Program Files\PowerShell\6'"
      #- powershell -command 'Set-Alias pwsh $poshcore\pwsh.exe'
      #- powershell -command 'Start-Sleep(15)'
  pre_build:
    commands:
      #- '& "c:\Program Files\PowerShell\6\pwsh.exe" $PSVersionTable'
      #- Set-Alias pwsh 'C:\Program Files\PowerShell\6\pwsh.exe'
      #- Get-Alias
      - "& 'C:\Program Files\PowerShell\6\pwsh.exe' -command '$PSVersionTable'"
      #- pwsh -command "$PSVersionTable"
      #- pwsh -command '.\install_modules.ps1'
  build:
    commands:
      - pwsh -command 'Get-Module -ListAvailable'
artifacts:
  files:
    #- '**/*'
  base-directory: 'PowerShellModule\Archive'