# This is a simple CodeBuild build file for PowerShell.
#  - pre_build step will ensure the Module Name / Version has not previously been built for production
#  - build step will perform the script analysis, pester tests, and Module compilation for publishing

version: 0.2

phases:
  install:
    commands:
      - powershell -command '.\configure_aws_credential.ps1'
      - aws s3 cp s3://ps-invoke-modules/PowerShell-6.1.1-win-x64.msi PowerShell-6.1.1-win-x64.msi --quiet
      - powershell -command "Start-Process .\PowerShell-6.1.1-win-x64.msi -ArgumentList '/qn /norestart' -Wait"
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''.\install_modules.ps1'''
  pre_build:
    commands:
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''Get-Module -ListAvailable'''
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''(Get-Module AWSPowerShell.NetCore -ListAvailable).Path'''
  build:
    commands:
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''Import-Module AWSPowerShell.NetCore;Get-SECSecretValue -SecretId PoshGramTokens -Region us-west-2'''
artifacts:
  files:
    - '**/*'
  base-directory: 'src\Archive'