# This is a simple CodeBuild build file for PowerShell.
#  - pre_build step will ensure the Module Name / Version has not previously been built for production
#  - build step will perform the script analysis, pester tests, and Module compilation for publishing

version: 0.2

phases:
  install:
    commands:
      - pwsh -command './configure_aws_credential.ps1'
      - pwsh -command './install_modules.ps1'
  pre_build:
    commands:
      - pwsh -command 'New-Item -Path /Test -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/Animation -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/Audio -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/Documents -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/PhotoGroup -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/Photos -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/VideoGroup -ItemType Directory | Out-Null'
      - pwsh -command 'New-Item -Path /Test/Videos -ItemType Directory | Out-Null
      - aws s3 cp s3://poshgram-test-files/jean.gif /Test/Animation/jean.gif --quiet
      - aws s3 cp s3://poshgram-test-files/Tobu-_-Syndec-Dusk-_NCS-Release_-YouTube.mp3 /Test/Audio/Tobu-_-Syndec-Dusk-_NCS-Release_-YouTube.mp3 --quiet
      - aws s3 cp s3://poshgram-test-files/customlog.txt /Test/Documents/customlog.txt --quiet
      - aws s3 cp s3://poshgram-test-files/beverly.jpg /Test/PhotoGroup/beverly.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/data.jpg /Test/PhotoGroup/data.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/geordi.jpg /Test/PhotoGroup/geordi.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/picard.jpg /Test/PhotoGroup/picard.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/riker.PNG /Test/PhotoGroup/riker.PNG --quiet
      - aws s3 cp s3://poshgram-test-files/troi.jpg /Test/PhotoGroup/troi.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/worf.jpg /Test/PhotoGroup/worf.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/Photo.jpg /Test/Photos/Photo.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/first_contact.mp4 /Test/VideoGroup/first_contact.mp4 --quiet
      - aws s3 cp s3://poshgram-test-files/root_beer.mp4 /Test/VideoGroup/root_beer.mp4 --quiet
      - aws s3 cp s3://poshgram-test-files/Intro.mp4 /Test/Videos/Intro.mp4 --quiet
      - pwsh -command 'Get-Module -ListAvailable'
      - pwsh -command '(Get-Module AWSPowerShell.NetCore -ListAvailable).Path'

  build:
    commands:
      - pwsh -command 'Import-Module AWSPowerShell.NetCore;Get-SECSecretValue -SecretId PoshGramTokens -Region us-west-2'
artifacts:
  files:
    - '**/*'
  base-directory: 'src/Archive'