# This is a simple CodeBuild build file for PowerShell.
#  - pre_build step will ensure the Module Name / Version has not previously been built for production
#  - build step will perform the script analysis, pester tests, and Module compilation for publishing

version: 0.2

phases:
  install:
    commands:
      - powershell -command '.\configure_aws_credential.ps1'
      - aws s3 cp s3://ps-invoke-modules/PowerShell-6.1.1-win-x64.msi PowerShell-6.1.1-win-x64.msi --quiet
      - powershell -command "Start-Process .\PowerShell-6.1.1-win-x64.msi -ArgumentList '/qn /norestart' -Wait"
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''.\install_modules.ps1'''
      - powershell -command '.\configure_aws_credential.ps1'
  pre_build:
    commands:
      - powershell -command 'New-Item -Path C:\Test -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\Animation -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\Audio -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\Documents -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\PhotoGroup -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\Photos -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\VideoGroup -ItemType Directory'
      - powershell -command 'New-Item -Path C:\Test\Videos -ItemType Directory'
      - aws s3 cp s3://poshgram-test-files/jean.gif C:\Test\Animation\jean.gif --quiet
      - aws s3 cp s3://poshgram-test-files/Tobu-_-Syndec-Dusk-_NCS-Release_-YouTube.mp3 C:\Test\Audio\Tobu-_-Syndec-Dusk-_NCS-Release_-YouTube.mp3 --quiet
      - aws s3 cp s3://poshgram-test-files/customlog.txt C:\Test\Documents\customlog.txt --quiet
      - aws s3 cp s3://poshgram-test-files/beverly.jpg C:\Test\PhotoGroup\beverly.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/data.jpg C:\Test\PhotoGroup\data.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/geordi.jpg C:\Test\PhotoGroup\geordi.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/picard.jpg C:\Test\PhotoGroup\picard.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/riker.PNG C:\Test\PhotoGroup\riker.PNG --quiet
      - aws s3 cp s3://poshgram-test-files/troi.jpg C:\Test\PhotoGroup\troi.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/worf.jpg C:\Test\PhotoGroup\worf.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/Photo.jpg C:\Test\Photos\Photo.jpg --quiet
      - aws s3 cp s3://poshgram-test-files/first_contact.mp4 C:\Test\VideoGroup\first_contact.mp4 --quiet
      - aws s3 cp s3://poshgram-test-files/root_beer.mp4 C:\Test\VideoGroup\root_beer.mp4 --quiet
      - aws s3 cp s3://poshgram-test-files/Intro.mp4 C:\Test\Videos\Intro.mp4 --quiet

  build:
    commands:
      - '& "C:\Program Files\PowerShell\6\pwsh.exe" -command ''Get-SECSecret -SecretId PoshGramTokens -Region us-west-2'''
artifacts:
  files:
    - '**/*'
  base-directory: 'src\Archive'